/*
 */

/*
 * DashboardFrame.java
 *
 * Created on Jan 17, 2011, 8:07:50 AM
 */

package org.docwhat.iated.ui;

import java.io.IOException;
import java.net.ServerSocket;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.sun.jersey.api.container.httpserver.HttpServerFactory;
import com.sun.net.httpserver.HttpServer;

/**
 *
 * @author jhurne
 */
public class DashboardFrame extends javax.swing.JFrame {

    private HttpServer server;

    /** Creates new form DashboardFrame */
    public DashboardFrame() throws IOException {
        initComponents();

        int defaultPort = findFreePort();
        String endpoint = String.format("http://localhost:%d/", defaultPort);

        server = HttpServerFactory.create(endpoint);
        server.start();
        System.out.println("Started server on: " + endpoint);
    }

  public int findFreePort() throws IOException {
    // From http://stackoverflow.com/questions/2675362/how-to-find-an-available-port
    // Also see http://stackoverflow.com/questions/3265825/finding-two-free-tcp-ports
    ServerSocket socket = null;
    try {
      socket = new ServerSocket(0);
      return socket.getLocalPort();
    } catch (Exception e) { 
        throw new IOException("no free port found");
    } finally {
        if (socket != null) {
            socket.close();
        }
    }
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preferencesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        preferencesButton.setText("Preferences");
        preferencesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(preferencesButton)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(preferencesButton)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preferencesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencesButtonActionPerformed
        PreferencesDialog dialog = new PreferencesDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_preferencesButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        server.stop(0);
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws IOException {
        useSwingSystemLookAndFeel();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DashboardFrame().setVisible(true);
                } catch (IOException e) {
                    //TODO Show an error dialog box.
                    System.err.println("Unable to start the server: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton preferencesButton;
    // End of variables declaration//GEN-END:variables


	/**
	 * Set the Swing look-and-feel to the System look-and-feel. The System look
	 * and feel ensures that Swing windows closely match the native OS windows.
	 */
	private static void useSwingSystemLookAndFeel() {
		try {
			// Use the System (native) look and feel
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

		} catch (UnsupportedLookAndFeelException e) {
			System.err.println("Unable to set the Swing Look and Feel. "
					+ "The default look and feel will be used instead.");
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			System.err.println("Unable to set the Swing Look and Feel. "
					+ "The default look and feel will be used instead.");
			e.printStackTrace();
		} catch (InstantiationException e) {
			System.err.println("Unable to set the Swing Look and Feel. "
					+ "The default look and feel will be used instead.");
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			System.err.println("Unable to set the Swing Look and Feel. "
					+ "The default look and feel will be used instead.");
			e.printStackTrace();
		}
	}
}
