package org.gerf.iated.ui;

/**
 * The preferences dialog for the Its All Text! application. This dialog box was
 * designed using the NetBeans GUI designer.
 */
public class PreferencesDialog extends javax.swing.JDialog {
	private static final long serialVersionUID = 1L;

	/** Creates new form PreferencesDialog */
	public PreferencesDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editorField = new javax.swing.JTextField();
        editorLabel = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        refreshRateLabel = new javax.swing.JLabel();
        refreshRateField = new javax.swing.JTextField();
        characterSetLabel = new javax.swing.JLabel();
        characterSetField = new javax.swing.JTextField();
        extensionsLabel = new javax.swing.JLabel();
        extensionsField = new javax.swing.JTextField();
        positionLabel = new javax.swing.JLabel();
        fadeRateLabel = new javax.swing.JLabel();
        hotKeyLabel = new javax.swing.JLabel();
        debuggingLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        upperLeftPosition = new javax.swing.JRadioButton();
        upperRightPosition = new javax.swing.JRadioButton();
        lowerLeftPosition = new javax.swing.JRadioButton();
        lowerRightPosition = new javax.swing.JRadioButton();
        disablePosition = new javax.swing.JRadioButton();
        fadeRateField = new javax.swing.JTextField();
        hotKeyField = new javax.swing.JTextField();
        removeAllBugsCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("It's All Text! Preferences");
        setResizable(false);

        editorField.setEditable(false);
        editorField.setText("/usr/bin/gvim");

        editorLabel.setText("Editor:");

        browseButton.setText("Browse");

        refreshRateLabel.setText("Seconds between refreshing:");

        refreshRateField.setText("3");

        characterSetLabel.setText("Character Set (default: UTF-8):");

        characterSetField.setText("UTF-8");

        extensionsLabel.setText("File Extensions:");

        extensionsField.setText(".xsl,.txt,.html,.css,.xml,.js");

        positionLabel.setText("Edit button position");

        fadeRateLabel.setText("Duration of button fade");

        hotKeyLabel.setText("Hot Key");

        debuggingLabel.setText("Debugging:");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        upperLeftPosition.setText("Upper Left");

        upperRightPosition.setText("Upper Right");

        lowerLeftPosition.setText("Lower Left");

        lowerRightPosition.setText("Lower Right");

        disablePosition.setText("Disable");

        fadeRateField.setText("2.3");

        hotKeyField.setText("<none>");

        removeAllBugsCheckbox.setText("Remove all bugs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extensionsLabel)
                    .addComponent(characterSetLabel)
                    .addComponent(positionLabel)
                    .addComponent(fadeRateLabel)
                    .addComponent(hotKeyLabel)
                    .addComponent(editorLabel)
                    .addComponent(debuggingLabel)
                    .addComponent(refreshRateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disablePosition, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(characterSetField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeAllBugsCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fadeRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(browseButton))
                    .addComponent(extensionsField, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lowerLeftPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upperLeftPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowerRightPosition)
                            .addComponent(upperRightPosition)))
                    .addComponent(editorField, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editorLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshRateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(characterSetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(characterSetLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extensionsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extensionsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upperLeftPosition)
                    .addComponent(upperRightPosition))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowerLeftPosition)
                    .addComponent(lowerRightPosition)
                    .addComponent(positionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disablePosition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fadeRateLabel)
                    .addComponent(fadeRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotKeyLabel)
                    .addComponent(hotKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(debuggingLabel)
                            .addComponent(removeAllBugsCheckbox))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				PreferencesDialog dialog = new PreferencesDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JTextField characterSetField;
    private javax.swing.JLabel characterSetLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel debuggingLabel;
    private javax.swing.JRadioButton disablePosition;
    private javax.swing.JTextField editorField;
    private javax.swing.JLabel editorLabel;
    private javax.swing.JTextField extensionsField;
    private javax.swing.JLabel extensionsLabel;
    private javax.swing.JTextField fadeRateField;
    private javax.swing.JLabel fadeRateLabel;
    private javax.swing.JTextField hotKeyField;
    private javax.swing.JLabel hotKeyLabel;
    private javax.swing.JRadioButton lowerLeftPosition;
    private javax.swing.JRadioButton lowerRightPosition;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JTextField refreshRateField;
    private javax.swing.JLabel refreshRateLabel;
    private javax.swing.JCheckBox removeAllBugsCheckbox;
    private javax.swing.JRadioButton upperLeftPosition;
    private javax.swing.JRadioButton upperRightPosition;
    // End of variables declaration//GEN-END:variables

}
